USE T_INLOCK;


INSERT INTO PERFIL (PERFIL) VALUES ('ADMIN');
INSERT INTO PERFIL (PERFIL) VALUES ('NORMAL');


INSERT INTO USUARIO (NOME,EMAIL,IDPERFIL) VALUES ('ARTHUR','ADMIN@ADMIN.COM','1');
INSERT INTO USUARIO (NOME,EMAIL,IDPERFIL) VALUES ('EMILIA','EM@EM.COM','2');
INSERT INTO USUARIO (NOME,EMAIL,IDPERFIL) VALUES ('TIAGO','T@T.COM','1');


INSERT INTO ESTUDIO(ESTUDIO, DATACRIACAO, IDUSUARIO) VALUES ('Blizzard','11-12-12','1');
INSERT INTO ESTUDIO(ESTUDIO, DATACRIACAO, IDUSUARIO) VALUES ('Rockstar ','24-03-2002','2');
INSERT INTO ESTUDIO(ESTUDIO, DATACRIACAO, IDUSUARIO) VALUES ('Studios ','05-05-05','2');

INSERT INTO JOGO (JOGO,DESCRICAO,DATALANCAMENTO,VALOR,IDESTUDIO) VALUES ('Diablo 3','é um jogo que contém bastante ação e é viciante, seja você um novato ou um fã','15-05-2012','99','1');
INSERT INTO JOGO (JOGO,DESCRICAO,DATALANCAMENTO,VALOR,IDESTUDIO) VALUES ('Red Dead Redemption II ','jogo eletrônico de ação-aventura western','26-10-2018','120','2');
