USE T_INLOCK;

--DQL
--SELEÇÃO

SELECT * FROM JOGO
SELECT * FROM PERFIL
SELECT * FROM ESTUDIO
SELECT * FROM USUARIO

SELECT U.NOME, U.IDPERFIL
FROM USUARIO U 

SELECT E.ESTUDIO, U.IDUSUARIO
FROM ESTUDIO E, USUARIO U

SELECT J.IDJOGO, E.IDESTUDIO
FROM JOGO J
JOIN ESTUDIO E
ON J.IDJOGO = E.IDESTUDIO

SELECT U.*,P.*
FROM USUARIO U, PERFIL P;